#
# Copyright (c) 2011-2015 LAAS/CNRS
# All rights reserved.
#
# Permission to use, copy, modify, and distribute this software for any purpose
# with or without   fee is hereby granted, provided   that the above  copyright
# notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
# REGARD TO THIS  SOFTWARE INCLUDING ALL  IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS. IN NO EVENT SHALL THE AUTHOR  BE LIABLE FOR ANY SPECIAL, DIRECT,
# INDIRECT, OR CONSEQUENTIAL DAMAGES OR  ANY DAMAGES WHATSOEVER RESULTING  FROM
# LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
# OTHER TORTIOUS ACTION,   ARISING OUT OF OR IN    CONNECTION WITH THE USE   OR
# PERFORMANCE OF THIS SOFTWARE.
#
#

# BIP model generation.

template usage {*}{
    "\n"
    "BIP model generation.\n"
    "\n"
    "This template generates a BIP of the component(s).\n"
    "\n"
    "Supported options:\n"
    "  -C, --directory=dir\toutput files in dir\n"
    "  -p, --preserve\tdo not overwrite existing files\n"
    "  -h. --help\t\tprint usage summary (this text)\n"
    " -t. --target\t\tspecify the target of the model:\n"
    "0 for execution-oriented BIP model, non-zero for verification-oriented models:\n"
    "1: verification model with urgencies, 2: with data variables, otherwise: with neither (larger models)" 
}

# require utility procs

template require ../common/typeutil.tcl

# defaults

set odir model/bip
engine mode +overwrite +move-if-change

# parse options
template options {
    -C - --directory	{ set odir [template arg] }
    -p - --preserve	{ engine mode -overwrite }
    -h - --help		{ puts [template usage]; exit 0 }
    -t - --target { set target [template arg] }
}


dotgen parse file [file join [dotgen template builtindir] common/genom.gen]

# parse input
set input [list]
foreach f $argv {
  dotgen parse file $f
  lappend input [file normalize $f]
}

set comp [dotgen components]

engine chdir $odir

# common header for all files (copyright info from .gen file)
set header {/* <"[--- Generated by [dotgen genom version]. Do not edit - ]"> */

<'if {![catch {dotgen input notice} notice]} {
  puts [lang c; comment $notice]
}'>
}

set compnames [list]
foreach c [dotgen components] {
	lappend compnames [$c name]
}

set outputname [join $compnames _]
set filename [join [list $outputname ".bip"] ""]
puts stderr "$filename" 


if {$target} {
if {$target == 1} {
template parse string $header file model_verification_urgencies.tcl \
file $filename
} else {
if {$target == 2} {
template parse string $header file model_verification_variables.tcl \
file $filename
} else {
template parse string $header file model_verification.tcl \
file $filename}}
	
} else {
template parse string $header file model_execution.tcl \
file $filename

}	


